analyzer:
  errors:
    unused_import: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    always_specify_types: true
    prefer_const_constructors: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    prefer_final_fields: true
    unnecessary_null_checks: true